'use strict';
(() => {
const $=id=>document.getElementById(id), data=window.MAP_DATA, geo=window.MAP_GEOGRAPHY;
if(!data||!geo){$('map-title').textContent='Map could not load';$('status').textContent='Please reload the page. Some map files could not be loaded.';return;}
const labels={T:'Target',L:'Trailer',P:'Peer',S:'Self',N:'No Data'};
const colors={T:'#22964f',L:'#dc3545',P:'#f2cd32',S:'#8b929a',N:'#000000'};
let reference=data.countries.indexOf('United States'),year=1999,timer=null,activeShape=null;
const ns='http://www.w3.org/2000/svg', map=$('map');
function svg(tag,attrs){const el=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);return el;}
map.append(svg('path',{d:geo.sphere,class:'ocean'}),svg('path',{d:geo.grid,class:'grid'}));
const shapes=geo.shapes.map(shape=>{const el=svg('path',{d:shape.path,class:'country'});map.append(el);el.addEventListener('pointermove',e=>showTooltip(shape,e));el.addEventListener('pointerleave',hideTooltip);el.addEventListener('click',e=>showTooltip(shape,e));let dot=null;if(shape.index>=0 && shape.area<3){dot=svg('circle',{cx:shape.center[0],cy:shape.center[1],r:2.7,class:'island'});map.append(dot);dot.addEventListener('pointermove',e=>showTooltip(shape,e));dot.addEventListener('pointerleave',hideTooltip);dot.addEventListener('click',e=>showTooltip(shape,e));}return {shape,el,dot};});
function code(index){if(index===reference)return 'S';return index<0?'N':data.matrices[year][reference][index];}
function hideTooltip(){activeShape=null;$('tooltip').hidden=true;}
function showTooltip(shape,event){activeShape=shape;const tip=$('tooltip');tip.textContent=`${shape.displayName||(shape.index>=0?data.countries[shape.index]:shape.name)} · ${labels[code(shape.index)]} · ${year}`;tip.hidden=false;const box=tip.parentElement.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(event.clientX-box.left+12,box.width-tip.offsetWidth-8))+'px';tip.style.top=Math.max(8,Math.min(event.clientY-box.top+12,box.height-tip.offsetHeight-8))+'px';}
for(const [i,name]of [...data.countries.entries()].sort((a,b)=>a[1].localeCompare(b[1]))){$('country').add(new Option(name,String(i)));}
for(const y of data.years)$('year').add(new Option(String(y),String(y)));
function render(){hideTooltip();$('country').value=reference;$('year').value=year;$('timeline').value=year;$('year-display').textContent=year;$('map-title').textContent=data.countries[reference];map.setAttribute('aria-label',`Country relationships from ${data.countries[reference]}, ${year}`);const counts={T:0,L:0,P:0,N:0};data.countries.forEach((_,i)=>{if(i!==reference)counts[code(i)]++;});for(const {shape,el,dot}of shapes){const c=code(shape.index);el.setAttribute('fill',colors[c]);if(dot)dot.setAttribute('fill',colors[c]);}
$('legend').replaceChildren();for(const c of ['T','L','P','S','N']){const item=document.createElement('span');item.className='legend-item';const swatch=document.createElement('i');swatch.className='swatch';swatch.style.setProperty('--color',colors[c]);const label=document.createElement('span');label.textContent=labels[c];item.append(swatch,label);if(c!=='S'){const count=document.createElement('span');count.className='count';count.textContent=counts[c];item.append(count);}$('legend').append(item);}
$('status').textContent=counts.N===196?`No Data for ${data.countries[reference]} in ${year}. Choose another year or country.`:`${counts.T} targets · ${counts.L} trailers · ${counts.P} peers${counts.N?` · ${counts.N} with No Data`:''}`;
const rows=document.createDocumentFragment();for(const [i,name]of [...data.countries.entries()].sort((a,b)=>a[1].localeCompare(b[1]))){const tr=document.createElement('tr'),country=document.createElement('td'),value=document.createElement('td');country.textContent=name;value.textContent=labels[code(i)];tr.append(country,value);rows.append(tr);}$('rows').replaceChildren(rows);
}
function pause(){if(timer)clearInterval(timer);timer=null;$('play').textContent='▶ Play';$('play').setAttribute('aria-label','Play timeline');$('play').setAttribute('aria-pressed','false');}
function play(){if(timer){pause();return;}if(year===2023){year=1999;render();}$('play').textContent='Ⅱ Pause';$('play').setAttribute('aria-label','Pause timeline');$('play').setAttribute('aria-pressed','true');timer=setInterval(()=>{year++;render();if(year>=2023)pause();},1000);}
$('country').addEventListener('change',()=>{reference=Number($('country').value);render();});$('year').addEventListener('change',()=>{pause();year=Number($('year').value);render();});$('timeline').addEventListener('input',()=>{pause();year=Number($('timeline').value);render();});$('play').addEventListener('click',play);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',pause);for(const id of ['country','year','timeline','play'])$(id).disabled=false;render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_map_view',description:'Select a reference country and year in the country relations map.',inputSchema:{type:'object',properties:{country:{type:'string',enum:data.countries},year:{type:'integer',minimum:1999,maximum:2023}},required:['country','year'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const i=data.countries.indexOf(input.country);if(i<0||!Number.isInteger(input.year)||!data.years.includes(input.year))throw Error('Choose a listed country and year from 1999 to 2023.');pause();reference=i;year=input.year;render();return {country:data.countries[reference],year,summary:$('status').textContent};}})).catch(()=>{});}catch{}}
})();
