'use strict';
(()=>{const $=id=>document.getElementById(id),names=window.MAP_DATA.countries,inputs=window.BUILDER_DATA,power=window.POWER_DATA.series.map(s=>s[24]),world=power.reduce((a,b)=>a+b,0),members=new Set(),search=$('builder-search'),list=$('builder-options');let active=-1;
function close(){list.hidden=true;search.setAttribute('aria-expanded','false');search.removeAttribute('aria-activedescendant');active=-1;}
function showRanks(combined){
 const panel=document.createElement('section');panel.className='builder-ranking';panel.setAttribute('aria-label','2023 ranking comparison');const heading=document.createElement('h3');heading.textContent='2023 ranking comparison';panel.append(heading);
 const entries=[...members].map(i=>({name:names[i],gpi:power[i],rank:1+power.filter(v=>v>power[i]).length,built:false}));entries.push({name:'Built country',gpi:combined,rank:1+power.filter((v,i)=>!members.has(i)&&v>combined).length,built:true});entries.sort((a,b)=>a.rank-b.rank||b.gpi-a.gpi||Number(b.built)-Number(a.built)||a.name.localeCompare(b.name));
 let previous=0;for(const e of entries){if(e.rank>previous+1){const gap=document.createElement('div');gap.className='builder-rank-gap';gap.textContent='⋮';gap.setAttribute('aria-label','Other ranks omitted');panel.append(gap);}const row=document.createElement('div');row.className='builder-rank-row'+(e.built?' is-built':'');const rank=document.createElement('strong');rank.className='builder-rank-number';rank.textContent='#'+e.rank;const text=document.createElement('div');const name=document.createElement('strong');name.textContent=e.name;const context=document.createElement('span');context.textContent=e.built?'After combining':'Original rank';text.append(name,context);row.append(rank,text);panel.append(row);previous=e.rank;}
 return panel;
}
function render(){const chips=$('builder-members');chips.replaceChildren();let gdp=0,pop=0,old=0;for(const i of members){gdp+=inputs[i][0];pop+=inputs[i][1];old+=power[i];const b=document.createElement('button');b.textContent=names[i]+' ×';b.setAttribute('aria-label','Remove '+names[i]);b.addEventListener('click',()=>{members.delete(i);render();});chips.append(b);}const result=$('builder-result');result.replaceChildren();if(!members.size){return;}const combined=1e12*gdp*gdp/pop,denominator=world-old+combined,share=100*combined/denominator;const value=document.createElement('p');value.className='builder-share';value.textContent=share.toLocaleString('en-US',{maximumFractionDigits:3})+'%';const label=document.createElement('p');label.textContent='of the adjusted world GPI total';const details=document.createElement('p');details.textContent=`${members.size} ${members.size===1?'country':'countries'} · Combined GDP (PPP): ${gdp.toLocaleString('en-US',{maximumFractionDigits:3})} billion international dollars · Population: ${pop.toLocaleString('en-US',{maximumFractionDigits:3})} million`;result.append(value,label,details,showRanks(combined));}
function filter(){list.replaceChildren();active=-1;search.removeAttribute('aria-activedescendant');const q=search.value.trim().toLocaleLowerCase();names.map((n,i)=>({n,i})).filter(e=>!members.has(e.i)&&e.n.toLocaleLowerCase().includes(q)).sort((a,b)=>a.n.localeCompare(b.n)).forEach(e=>{const b=document.createElement('button');b.role='option';b.id='builder-option-'+e.i;b.tabIndex=-1;b.textContent=e.n;b.addEventListener('mousedown',e=>e.preventDefault());b.addEventListener('click',()=>{members.add(e.i);search.value='';close();render();});list.append(b);});if(!list.children.length){const empty=document.createElement('span');empty.textContent='No matching countries';list.append(empty);}list.hidden=false;search.setAttribute('aria-expanded','true');}
search.addEventListener('focus',filter);search.addEventListener('input',filter);search.addEventListener('blur',close);search.addEventListener('keydown',e=>{if(e.key==='Escape')close();else if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(list.hidden)filter();const options=[...list.querySelectorAll('button')];if(!options.length)return;active=(active+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;options.forEach((o,i)=>o.setAttribute('aria-selected',String(i===active)));search.setAttribute('aria-activedescendant',options[active].id);options[active].scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&!list.hidden){e.preventDefault();list.querySelectorAll('button')[Math.max(0,active)]?.click();}});
const tabs=[$('power-ranking-tab'),$('builder-tab'),$('concentration-tab')];function activate(i){tabs.forEach((t,j)=>{t.setAttribute('aria-selected',String(i===j));t.tabIndex=i===j?0:-1;});$('power-ranking-panel').hidden=i!==0;$('builder-panel').hidden=i!==1;$('concentration-panel').hidden=i!==2;}tabs.forEach((t,i)=>{t.addEventListener('click',()=>activate(i));t.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;activate(n);tabs[n].focus();});});render();})();
